version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: chore
      include: scope
    groups:
      tauri:
        patterns: ["tauri*"]

  - package-ecosystem: bun
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: chore
      include: scope
    groups:
      svelte:
        patterns: ["svelte*", "@sveltejs/*"]
      tauri:
        patterns: ["@tauri-apps/*"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: chore
      include: scope
